"""init

Revision ID: dc7192856123
Revises: 
Create Date: 2026-02-21 07:29:35.619677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc7192856123'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medecin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('specialite', sa.String(length=100), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('dateNaissance', sa.Date(), nullable=True),
    sa.Column('sexe', sa.String(length=20), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('dateImplantation', sa.Date(), nullable=True),
    sa.Column('idImplant', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dateIncident', sa.Date(), nullable=False),
    sa.Column('heureIncident', sa.Time(), nullable=False),
    sa.Column('gravite', sa.Enum('mineur', 'modere', 'majeur', 'critique', name='graviteenum'), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('statut', sa.Enum('ouvert', 'en_cours', 'resolu', 'ferme', name='statutenum'), nullable=False),
    sa.Column('idPatient', sa.Integer(), nullable=False),
    sa.Column('idImplant', sa.Integer(), nullable=True),
    sa.Column('idProcesseur', sa.Integer(), nullable=True),
    sa.Column('idMedecin', sa.Integer(), nullable=True),
    sa.Column('dateCreation', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('dateModification', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idMedecin'], ['medecin.id'], ),
    sa.ForeignKeyConstraint(['idPatient'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suiviincident',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dateSuivi', sa.Date(), nullable=False),
    sa.Column('actionsPrises', sa.Text(), nullable=False),
    sa.Column('idIncident', sa.Integer(), nullable=False),
    sa.Column('idMedecin', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idIncident'], ['incident.id'], ),
    sa.ForeignKeyConstraint(['idMedecin'], ['medecin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suiviincident')
    op.drop_table('incident')
    op.drop_table('patient')
    op.drop_table('medecin')
    # ### end Alembic commands ###
